name: perf-calculator

services:
  my_service:
    image: judevops.azurecr.io/perf-calculator
    container_name: api-calculator-perf
    ports:
      - "5000:5000"  
    deploy:
      resources:
        limits:
          memory: 1.5g  
